name: 参加登録
description: Maximum WSH 2022 の参加登録フォームです
title: "[参加登録]"
labels:
  - registration
body:
  - type: markdown
    attributes:
      value: |
        ↑ **タイトルはそのままで OK です**

        # ようこそ Maximum WSH 2022 へ！

        **参加する前に、レギュレーションを確認してください**

         - [レギュレーション](https://github.com/CyberAgentHack/web-speed-hackathon-2022-leaderboard/blob/main/docs/REGULATION.md)
  - type: markdown
    attributes:
      value: |
        ## 計測対象の URL

        [課題のソースコード](https://github.com/CyberAgentHack/web-speed-hackathon-2022) から、アプリケーションをデプロイして、URL を提出してください
  - type: input
    id: target-url
    attributes:
      label: "計測対象の URL {{url}}"
      placeholder: e.g.) https://web-speed-hackathon-2022.example.com/
    validations:
      required: true
